# Generated by Django 4.1.2 on 2022-12-17 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autobus',
            fields=[
                ('model', models.CharField(max_length=30)),
                ('broj', models.DecimalField(decimal_places=0, max_digits=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Linija',
            fields=[
                ('ime', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('vrijeme_polaska', models.TimeField()),
                ('autobus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.autobus')),
            ],
        ),
        migrations.CreateModel(
            name='Stanica',
            fields=[
                ('ime', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('adresa', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Vozac',
            fields=[
                ('ime', models.CharField(max_length=30)),
                ('prezime', models.CharField(max_length=30)),
                ('OIB', models.DecimalField(decimal_places=0, max_digits=11, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='StanicaLinija',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linija', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.linija')),
                ('stanica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.stanica')),
            ],
        ),
        migrations.AddField(
            model_name='stanica',
            name='linije',
            field=models.ManyToManyField(through='main.StanicaLinija', to='main.linija'),
        ),
        migrations.AddField(
            model_name='linija',
            name='stanice',
            field=models.ManyToManyField(through='main.StanicaLinija', to='main.stanica'),
        ),
        migrations.AddField(
            model_name='autobus',
            name='vozac',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.vozac'),
        ),
    ]
